# Generated by Django 4.2.1 on 2023-07-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_remove_receipt_processed_data_receiptitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptitem',
            old_name='assigned_users',
            new_name='assignees',
        ),
    ]
