# Generated by Django 4.2.1 on 2023-06-24 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr', '0002_receipt_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='processed_data',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
