# Generated by Django 4.2.1 on 2023-06-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_receipt_processed_data_alter_receipt_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='processed_data',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
