# Generated by Django 4.2.1 on 2023-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_receipt_date_created_receipt_discounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='discounts',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='service_charge',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
