# Generated by Django 4.2.1 on 2023-06-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_alter_receipt_image_alter_receipt_processed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
