# Generated by Django 4.2.1 on 2023-06-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_alter_receipt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
