# Generated by Django 4.2.1 on 2023-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_alter_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='my_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
