# Generated by Django 4.2.1 on 2023-06-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_remove_profile_id_profile_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
