# Generated by Django 4.2.1 on 2023-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(default='hello', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
