# Generated by Django 4.2.1 on 2023-06-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_remove_profile_username_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
